// Code generated by pigeon; DO NOT EDIT.

package mini

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"codeberg.org/uzu/saint-hubbins/internal/core"
)

func parseFloat(s string) (float64, error) {
	return strconv.ParseFloat(s, 64)
}

func parseSampleN(s string) any {
	if n, err := strconv.Atoi(s); err == nil {
		return n
	}
	if f, err := strconv.ParseFloat(s, 64); err == nil {
		return f
	}
	return s
}

var g = &grammar{
	rules: []*rule{
		{
			name: "MiniFile",
			pos:  position{line: 27, col: 1, offset: 479},
			expr: &actionExpr{
				pos: position{line: 27, col: 13, offset: 491},
				run: (*parser).callonMiniFile1,
				expr: &seqExpr{
					pos: position{line: 27, col: 13, offset: 491},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 27, col: 13, offset: 491},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 27, col: 15, offset: 493},
							label: "seq",
							expr: &ruleRefExpr{
								pos:  position{line: 27, col: 19, offset: 497},
								name: "Sequence",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 27, col: 28, offset: 506},
							name: "_",
						},
						&zeroOrMoreExpr{
							pos: position{line: 27, col: 30, offset: 508},
							expr: &seqExpr{
								pos: position{line: 27, col: 31, offset: 509},
								exprs: []any{
									&notExpr{
										pos: position{line: 27, col: 31, offset: 509},
										expr: &ruleRefExpr{
											pos:  position{line: 27, col: 32, offset: 510},
											name: "EOF",
										},
									},
									&anyMatcher{
										line: 27, col: 36, offset: 514,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Sequence",
			pos:  position{line: 31, col: 1, offset: 540},
			expr: &actionExpr{
				pos: position{line: 31, col: 13, offset: 552},
				run: (*parser).callonSequence1,
				expr: &seqExpr{
					pos: position{line: 31, col: 13, offset: 552},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 31, col: 13, offset: 552},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 31, col: 19, offset: 558},
								name: "Element",
							},
						},
						&labeledExpr{
							pos:   position{line: 31, col: 27, offset: 566},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 31, col: 32, offset: 571},
								expr: &seqExpr{
									pos: position{line: 31, col: 33, offset: 572},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 31, col: 33, offset: 572},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 31, col: 35, offset: 574},
											name: "Element",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Element",
			pos:  position{line: 48, col: 1, offset: 948},
			expr: &actionExpr{
				pos: position{line: 48, col: 12, offset: 959},
				run: (*parser).callonElement1,
				expr: &seqExpr{
					pos: position{line: 48, col: 12, offset: 959},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 48, col: 12, offset: 959},
							label: "atom",
							expr: &ruleRefExpr{
								pos:  position{line: 48, col: 17, offset: 964},
								name: "Atom",
							},
						},
						&labeledExpr{
							pos:   position{line: 48, col: 22, offset: 969},
							label: "ops",
							expr: &zeroOrMoreExpr{
								pos: position{line: 48, col: 26, offset: 973},
								expr: &seqExpr{
									pos: position{line: 48, col: 27, offset: 974},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 48, col: 27, offset: 974},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 48, col: 29, offset: 976},
											name: "Operator",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Atom",
			pos:  position{line: 113, col: 1, offset: 2958},
			expr: &choiceExpr{
				pos: position{line: 113, col: 9, offset: 2966},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 113, col: 9, offset: 2966},
						run: (*parser).callonAtom2,
						expr: &labeledExpr{
							pos:   position{line: 113, col: 9, offset: 2966},
							label: "r",
							expr: &ruleRefExpr{
								pos:  position{line: 113, col: 11, offset: 2968},
								name: "Rest",
							},
						},
					},
					&actionExpr{
						pos: position{line: 114, col: 9, offset: 3012},
						run: (*parser).callonAtom5,
						expr: &labeledExpr{
							pos:   position{line: 114, col: 9, offset: 3012},
							label: "s",
							expr: &ruleRefExpr{
								pos:  position{line: 114, col: 11, offset: 3014},
								name: "Sample",
							},
						},
					},
					&actionExpr{
						pos: position{line: 115, col: 9, offset: 3047},
						run: (*parser).callonAtom8,
						expr: &labeledExpr{
							pos:   position{line: 115, col: 9, offset: 3047},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 115, col: 11, offset: 3049},
								name: "Number",
							},
						},
					},
					&actionExpr{
						pos: position{line: 116, col: 9, offset: 3110},
						run: (*parser).callonAtom11,
						expr: &labeledExpr{
							pos:   position{line: 116, col: 9, offset: 3110},
							label: "w",
							expr: &ruleRefExpr{
								pos:  position{line: 116, col: 11, offset: 3112},
								name: "Word",
							},
						},
					},
					&actionExpr{
						pos: position{line: 117, col: 9, offset: 3171},
						run: (*parser).callonAtom14,
						expr: &seqExpr{
							pos: position{line: 117, col: 9, offset: 3171},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 117, col: 9, offset: 3171},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&ruleRefExpr{
									pos:  position{line: 117, col: 13, offset: 3175},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 117, col: 15, offset: 3177},
									label: "seq",
									expr: &ruleRefExpr{
										pos:  position{line: 117, col: 19, offset: 3181},
										name: "Sequence",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 117, col: 28, offset: 3190},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 117, col: 30, offset: 3192},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 118, col: 9, offset: 3224},
						run: (*parser).callonAtom22,
						expr: &seqExpr{
							pos: position{line: 118, col: 9, offset: 3224},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 118, col: 9, offset: 3224},
									val:        "<",
									ignoreCase: false,
									want:       "\"<\"",
								},
								&ruleRefExpr{
									pos:  position{line: 118, col: 13, offset: 3228},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 118, col: 15, offset: 3230},
									label: "seq",
									expr: &ruleRefExpr{
										pos:  position{line: 118, col: 19, offset: 3234},
										name: "Sequence",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 118, col: 28, offset: 3243},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 118, col: 30, offset: 3245},
									val:        ">",
									ignoreCase: false,
									want:       "\">\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 119, col: 9, offset: 3306},
						run: (*parser).callonAtom30,
						expr: &seqExpr{
							pos: position{line: 119, col: 9, offset: 3306},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 119, col: 9, offset: 3306},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&ruleRefExpr{
									pos:  position{line: 119, col: 13, offset: 3310},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 119, col: 15, offset: 3312},
									label: "inner",
									expr: &ruleRefExpr{
										pos:  position{line: 119, col: 21, offset: 3318},
										name: "PolymeterInner",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 119, col: 36, offset: 3333},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 119, col: 38, offset: 3335},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
								&labeledExpr{
									pos:   position{line: 119, col: 42, offset: 3339},
									label: "suffix",
									expr: &zeroOrOneExpr{
										pos: position{line: 119, col: 49, offset: 3346},
										expr: &ruleRefExpr{
											pos:  position{line: 119, col: 49, offset: 3346},
											name: "PolymeterSuffix",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Sample",
			pos:  position{line: 144, col: 1, offset: 4123},
			expr: &actionExpr{
				pos: position{line: 144, col: 11, offset: 4133},
				run: (*parser).callonSample1,
				expr: &seqExpr{
					pos: position{line: 144, col: 11, offset: 4133},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 144, col: 11, offset: 4133},
							label: "base",
							expr: &ruleRefExpr{
								pos:  position{line: 144, col: 16, offset: 4138},
								name: "Word",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 144, col: 21, offset: 4143},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 144, col: 23, offset: 4145},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&ruleRefExpr{
							pos:  position{line: 144, col: 27, offset: 4149},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 144, col: 29, offset: 4151},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 144, col: 31, offset: 4153},
								name: "SampleN",
							},
						},
					},
				},
			},
		},
		{
			name: "SampleN",
			pos:  position{line: 150, col: 1, offset: 4294},
			expr: &choiceExpr{
				pos: position{line: 150, col: 12, offset: 4305},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 150, col: 12, offset: 4305},
						name: "Number",
					},
					&ruleRefExpr{
						pos:  position{line: 150, col: 21, offset: 4314},
						name: "Word",
					},
				},
			},
		},
		{
			name: "PolymeterInner",
			pos:  position{line: 152, col: 1, offset: 4320},
			expr: &actionExpr{
				pos: position{line: 152, col: 19, offset: 4338},
				run: (*parser).callonPolymeterInner1,
				expr: &seqExpr{
					pos: position{line: 152, col: 19, offset: 4338},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 152, col: 19, offset: 4338},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 152, col: 25, offset: 4344},
								name: "Sequence",
							},
						},
						&labeledExpr{
							pos:   position{line: 152, col: 34, offset: 4353},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 152, col: 39, offset: 4358},
								expr: &seqExpr{
									pos: position{line: 152, col: 40, offset: 4359},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 152, col: 40, offset: 4359},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 152, col: 42, offset: 4361},
											val:        ",",
											ignoreCase: false,
											want:       "\",\"",
										},
										&ruleRefExpr{
											pos:  position{line: 152, col: 46, offset: 4365},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 152, col: 48, offset: 4367},
											name: "Sequence",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PolymeterSuffix",
			pos:  position{line: 164, col: 1, offset: 4668},
			expr: &choiceExpr{
				pos: position{line: 164, col: 20, offset: 4687},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 164, col: 20, offset: 4687},
						run: (*parser).callonPolymeterSuffix2,
						expr: &seqExpr{
							pos: position{line: 164, col: 20, offset: 4687},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 164, col: 20, offset: 4687},
									val:        "%",
									ignoreCase: false,
									want:       "\"%\"",
								},
								&ruleRefExpr{
									pos:  position{line: 164, col: 24, offset: 4691},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 164, col: 26, offset: 4693},
									label: "n",
									expr: &ruleRefExpr{
										pos:  position{line: 164, col: 28, offset: 4695},
										name: "Number",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 165, col: 19, offset: 4753},
						run: (*parser).callonPolymeterSuffix8,
						expr: &seqExpr{
							pos: position{line: 165, col: 19, offset: 4753},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 165, col: 19, offset: 4753},
									val:        "*",
									ignoreCase: false,
									want:       "\"*\"",
								},
								&ruleRefExpr{
									pos:  position{line: 165, col: 23, offset: 4757},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 165, col: 25, offset: 4759},
									label: "n",
									expr: &ruleRefExpr{
										pos:  position{line: 165, col: 27, offset: 4761},
										name: "Number",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 166, col: 19, offset: 4819},
						run: (*parser).callonPolymeterSuffix14,
						expr: &seqExpr{
							pos: position{line: 166, col: 19, offset: 4819},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 166, col: 19, offset: 4819},
									val:        "/",
									ignoreCase: false,
									want:       "\"/\"",
								},
								&ruleRefExpr{
									pos:  position{line: 166, col: 23, offset: 4823},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 166, col: 25, offset: 4825},
									label: "n",
									expr: &ruleRefExpr{
										pos:  position{line: 166, col: 27, offset: 4827},
										name: "Number",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Word",
			pos:  position{line: 168, col: 1, offset: 4868},
			expr: &actionExpr{
				pos: position{line: 168, col: 9, offset: 4876},
				run: (*parser).callonWord1,
				expr: &oneOrMoreExpr{
					pos: position{line: 168, col: 9, offset: 4876},
					expr: &charClassMatcher{
						pos:        position{line: 168, col: 9, offset: 4876},
						val:        "[a-zA-Z0-9#_^.~-]",
						chars:      []rune{'#', '_', '^', '.', '~', '-'},
						ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 169, col: 1, offset: 4926},
			expr: &actionExpr{
				pos: position{line: 169, col: 11, offset: 4936},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 169, col: 11, offset: 4936},
					exprs: []any{
						&oneOrMoreExpr{
							pos: position{line: 169, col: 11, offset: 4936},
							expr: &charClassMatcher{
								pos:        position{line: 169, col: 11, offset: 4936},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 169, col: 18, offset: 4943},
							expr: &seqExpr{
								pos: position{line: 169, col: 19, offset: 4944},
								exprs: []any{
									&litMatcher{
										pos:        position{line: 169, col: 19, offset: 4944},
										val:        ".",
										ignoreCase: false,
										want:       "\".\"",
									},
									&oneOrMoreExpr{
										pos: position{line: 169, col: 23, offset: 4948},
										expr: &charClassMatcher{
											pos:        position{line: 169, col: 23, offset: 4948},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Rest",
			pos:  position{line: 170, col: 1, offset: 4988},
			expr: &choiceExpr{
				pos: position{line: 170, col: 9, offset: 4996},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 170, col: 9, offset: 4996},
						val:        "~",
						ignoreCase: false,
						want:       "\"~\"",
					},
					&litMatcher{
						pos:        position{line: 170, col: 15, offset: 5002},
						val:        "-",
						ignoreCase: false,
						want:       "\"-\"",
					},
					&actionExpr{
						pos: position{line: 170, col: 21, offset: 5008},
						run: (*parser).callonRest4,
						expr: &litMatcher{
							pos:        position{line: 170, col: 21, offset: 5008},
							val:        "_",
							ignoreCase: false,
							want:       "\"_\"",
						},
					},
				},
			},
		},
		{
			name: "Operator",
			pos:  position{line: 171, col: 1, offset: 5043},
			expr: &choiceExpr{
				pos: position{line: 171, col: 13, offset: 5055},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 171, col: 13, offset: 5055},
						name: "EuclidOp",
					},
					&ruleRefExpr{
						pos:  position{line: 171, col: 24, offset: 5066},
						name: "WeightOp",
					},
					&ruleRefExpr{
						pos:  position{line: 171, col: 35, offset: 5077},
						name: "FastOp",
					},
					&ruleRefExpr{
						pos:  position{line: 171, col: 44, offset: 5086},
						name: "SlowOp",
					},
					&ruleRefExpr{
						pos:  position{line: 171, col: 53, offset: 5095},
						name: "DegradeOp",
					},
					&ruleRefExpr{
						pos:  position{line: 171, col: 65, offset: 5107},
						name: "ReplicateOp",
					},
				},
			},
		},
		{
			name: "FastOp",
			pos:  position{line: 172, col: 1, offset: 5119},
			expr: &actionExpr{
				pos: position{line: 172, col: 11, offset: 5129},
				run: (*parser).callonFastOp1,
				expr: &seqExpr{
					pos: position{line: 172, col: 11, offset: 5129},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 172, col: 11, offset: 5129},
							val:        "*",
							ignoreCase: false,
							want:       "\"*\"",
						},
						&ruleRefExpr{
							pos:  position{line: 172, col: 15, offset: 5133},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 172, col: 17, offset: 5135},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 172, col: 19, offset: 5137},
								name: "Number",
							},
						},
					},
				},
			},
		},
		{
			name: "SlowOp",
			pos:  position{line: 173, col: 1, offset: 5177},
			expr: &actionExpr{
				pos: position{line: 173, col: 11, offset: 5187},
				run: (*parser).callonSlowOp1,
				expr: &seqExpr{
					pos: position{line: 173, col: 11, offset: 5187},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 173, col: 11, offset: 5187},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
						&ruleRefExpr{
							pos:  position{line: 173, col: 15, offset: 5191},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 173, col: 17, offset: 5193},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 173, col: 19, offset: 5195},
								name: "Number",
							},
						},
					},
				},
			},
		},
		{
			name: "EuclidOp",
			pos:  position{line: 174, col: 1, offset: 5235},
			expr: &actionExpr{
				pos: position{line: 174, col: 13, offset: 5247},
				run: (*parser).callonEuclidOp1,
				expr: &seqExpr{
					pos: position{line: 174, col: 13, offset: 5247},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 174, col: 13, offset: 5247},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 174, col: 17, offset: 5251},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 174, col: 19, offset: 5253},
							label: "pulses",
							expr: &ruleRefExpr{
								pos:  position{line: 174, col: 26, offset: 5260},
								name: "Number",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 174, col: 33, offset: 5267},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 174, col: 35, offset: 5269},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 174, col: 39, offset: 5273},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 174, col: 41, offset: 5275},
							label: "steps",
							expr: &ruleRefExpr{
								pos:  position{line: 174, col: 47, offset: 5281},
								name: "Number",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 174, col: 54, offset: 5288},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 174, col: 56, offset: 5290},
							expr: &seqExpr{
								pos: position{line: 174, col: 57, offset: 5291},
								exprs: []any{
									&litMatcher{
										pos:        position{line: 174, col: 57, offset: 5291},
										val:        ",",
										ignoreCase: false,
										want:       "\",\"",
									},
									&ruleRefExpr{
										pos:  position{line: 174, col: 61, offset: 5295},
										name: "_",
									},
									&labeledExpr{
										pos:   position{line: 174, col: 63, offset: 5297},
										label: "rotation",
										expr: &ruleRefExpr{
											pos:  position{line: 174, col: 72, offset: 5306},
											name: "Number",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 174, col: 79, offset: 5313},
										name: "_",
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 174, col: 83, offset: 5317},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "WeightOp",
			pos:  position{line: 175, col: 1, offset: 5352},
			expr: &actionExpr{
				pos: position{line: 175, col: 13, offset: 5364},
				run: (*parser).callonWeightOp1,
				expr: &seqExpr{
					pos: position{line: 175, col: 13, offset: 5364},
					exprs: []any{
						&choiceExpr{
							pos: position{line: 175, col: 14, offset: 5365},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 175, col: 14, offset: 5365},
									val:        "@",
									ignoreCase: false,
									want:       "\"@\"",
								},
								&litMatcher{
									pos:        position{line: 175, col: 20, offset: 5371},
									val:        "_",
									ignoreCase: false,
									want:       "\"_\"",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 175, col: 25, offset: 5376},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 175, col: 27, offset: 5378},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 175, col: 29, offset: 5380},
								name: "Number",
							},
						},
					},
				},
			},
		},
		{
			name: "DegradeOp",
			pos:  position{line: 176, col: 1, offset: 5418},
			expr: &actionExpr{
				pos: position{line: 176, col: 14, offset: 5431},
				run: (*parser).callonDegradeOp1,
				expr: &seqExpr{
					pos: position{line: 176, col: 14, offset: 5431},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 176, col: 14, offset: 5431},
							val:        "?",
							ignoreCase: false,
							want:       "\"?\"",
						},
						&ruleRefExpr{
							pos:  position{line: 176, col: 18, offset: 5435},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 176, col: 20, offset: 5437},
							label: "n",
							expr: &zeroOrOneExpr{
								pos: position{line: 176, col: 22, offset: 5439},
								expr: &ruleRefExpr{
									pos:  position{line: 176, col: 22, offset: 5439},
									name: "Number",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ReplicateOp",
			pos:  position{line: 177, col: 1, offset: 5478},
			expr: &choiceExpr{
				pos: position{line: 177, col: 16, offset: 5493},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 177, col: 16, offset: 5493},
						run: (*parser).callonReplicateOp2,
						expr: &seqExpr{
							pos: position{line: 177, col: 16, offset: 5493},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 177, col: 16, offset: 5493},
									val:        "!",
									ignoreCase: false,
									want:       "\"!\"",
								},
								&ruleRefExpr{
									pos:  position{line: 177, col: 20, offset: 5497},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 177, col: 22, offset: 5499},
									label: "n",
									expr: &zeroOrOneExpr{
										pos: position{line: 177, col: 24, offset: 5501},
										expr: &ruleRefExpr{
											pos:  position{line: 177, col: 24, offset: 5501},
											name: "Number",
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 178, col: 17, offset: 5556},
						run: (*parser).callonReplicateOp9,
						expr: &seqExpr{
							pos: position{line: 178, col: 17, offset: 5556},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 178, col: 17, offset: 5556},
									val:        "!",
									ignoreCase: false,
									want:       "\"!\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 178, col: 21, offset: 5560},
									expr: &litMatcher{
										pos:        position{line: 178, col: 21, offset: 5560},
										val:        "!",
										ignoreCase: false,
										want:       "\"!\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 179, col: 1, offset: 5596},
			expr: &actionExpr{
				pos: position{line: 179, col: 6, offset: 5601},
				run: (*parser).callon_1,
				expr: &zeroOrMoreExpr{
					pos: position{line: 179, col: 6, offset: 5601},
					expr: &charClassMatcher{
						pos:        position{line: 179, col: 6, offset: 5601},
						val:        "[ \\t\\n\\r]",
						chars:      []rune{' ', '\t', '\n', '\r'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 180, col: 1, offset: 5631},
			expr: &actionExpr{
				pos: position{line: 180, col: 8, offset: 5638},
				run: (*parser).callonEOF1,
				expr: &notExpr{
					pos: position{line: 180, col: 8, offset: 5638},
					expr: &anyMatcher{
						line: 180, col: 9, offset: 5639,
					},
				},
			},
		},
	},
}

func (c *current) onMiniFile1(seq any) (any, error) {
	return seq, nil
}

func (p *parser) callonMiniFile1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMiniFile1(stack["seq"])
}

func (c *current) onSequence1(first, rest any) (any, error) {
	pats := []core.Pattern{first.(core.Pattern)}
	if restSlice, ok := rest.([]interface{}); ok {
		for _, v := range restSlice {
			if arr, ok := v.([]interface{}); ok && len(arr) == 2 {
				if pat, ok := arr[1].(core.Pattern); ok {
					pats = append(pats, pat)
				}
			}
		}
	}
	if len(pats) == 1 {
		return pats[0], nil
	}
	return core.FastCat(pats...), nil
}

func (p *parser) callonSequence1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSequence1(stack["first"], stack["rest"])
}

func (c *current) onElement1(atom, ops any) (any, error) {
	pat := atom.(core.Pattern)
	if opsSlice, ok := ops.([]interface{}); ok {
		for _, v := range opsSlice {
			if arr, ok := v.([]interface{}); ok && len(arr) == 2 {
				if op, ok := arr[1].(string); ok {
					if len(op) == 0 {
						continue
					}
					switch op[0] {
					case '*':
						if val, err := parseFloat(op[1:]); err == nil {
							pat = pat.FastF(core.FractionFromFloat(val))
						}
					case '/':
						if val, err := parseFloat(op[1:]); err == nil {
							pat = pat.SlowF(core.FractionFromFloat(val))
						}
					case '?':
						prob := 0.5
						if len(op) > 1 {
							if val, err := parseFloat(op[1:]); err == nil {
								prob = val
							}
						}
						pat = pat.DegradeBy(prob)
					case '(':
						// Euclid "(pulses,steps)" or "(pulses,steps,rotation)"
						inner := strings.Trim(op, "()")
						parts := strings.Split(inner, ",")
						if len(parts) >= 2 {
							pulses, _ := strconv.Atoi(strings.TrimSpace(parts[0]))
							steps, _ := strconv.Atoi(strings.TrimSpace(parts[1]))
							rotation := 0
							if len(parts) >= 3 {
								rotation, _ = strconv.Atoi(strings.TrimSpace(parts[2]))
							}
							if rotation != 0 {
								pat = pat.EuclidRot(pulses, steps, rotation)
							} else {
								pat = pat.Euclid(pulses, steps)
							}
						}
					case '@', '_':
						// Weight: "@2" or "_2" -> WithSteps weight
						if val, err := parseFloat(op[1:]); err == nil && val != 0 {
							w := val
							pat = pat.WithSteps(func(f core.Fraction) core.Fraction { return f.Mul(core.FractionFromFloat(w)) })
						}
					case '!':
						// Replicate: "!" or "!2" or "!!" (count !)
						// op is "!" or "!2" or "!!" etc — count ! and parse number
						reps := strings.Count(op, "!")
						numStr := strings.Trim(op, "!")
						if numStr != "" {
							if v, err := strconv.Atoi(strings.TrimSpace(numStr)); err == nil {
								reps = v
							}
						}
						if reps <= 1 {
							reps = 2
						}
						pat = pat.Ply(reps)
					}
				}
			}
		}
	}
	return pat, nil
}

func (p *parser) callonElement1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onElement1(stack["atom"], stack["ops"])
}

func (c *current) onAtom2(r any) (any, error) {
	return core.Silence(), nil
}

func (p *parser) callonAtom2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAtom2(stack["r"])
}

func (c *current) onAtom5(s any) (any, error) {
	return s, nil
}

func (p *parser) callonAtom5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAtom5(stack["s"])
}

func (c *current) onAtom8(n any) (any, error) {
	return core.Pure(string(n.(string))), nil
}

func (p *parser) callonAtom8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAtom8(stack["n"])
}

func (c *current) onAtom11(w any) (any, error) {
	return core.Pure(string(w.(string))), nil
}

func (p *parser) callonAtom11() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAtom11(stack["w"])
}

func (c *current) onAtom14(seq any) (any, error) {
	return seq, nil
}

func (p *parser) callonAtom14() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAtom14(stack["seq"])
}

func (c *current) onAtom22(seq any) (any, error) {
	return core.SlowCat(seq.(core.Pattern)), nil
}

func (p *parser) callonAtom22() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAtom22(stack["seq"])
}

func (c *current) onAtom30(inner, suffix any) (any, error) {
	seqs := inner.([]core.Pattern)
	var base core.Pattern
	if len(seqs) == 1 {
		base = seqs[0]
	} else {
		base = core.Stack(seqs...)
	}
	if suffix != nil {
		if s, ok := suffix.(string); ok && len(s) > 0 {
			switch s[0] {
			case '*':
				if val, err := parseFloat(s[1:]); err == nil {
					base = base.FastF(core.FractionFromFloat(val))
				}
			case '/':
				if val, err := parseFloat(s[1:]); err == nil {
					base = base.SlowF(core.FractionFromFloat(val))
				}
			case '%':
				// steps-per-cycle: for now keep base (Polymeter already stacked)
				// Could apply WithSteps but keep as base to avoid empty
			}
		}
	}
	return base, nil

}

func (p *parser) callonAtom30() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAtom30(stack["inner"], stack["suffix"])
}

func (c *current) onSample1(base, n any) (any, error) {
	s := string(base.(string))
	nStr := string(n.(string))
	return core.Pure(map[string]any{"s": s, "n": parseSampleN(nStr)}), nil
}

func (p *parser) callonSample1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSample1(stack["base"], stack["n"])
}

func (c *current) onPolymeterInner1(first, rest any) (any, error) {
	pats := []core.Pattern{first.(core.Pattern)}
	if restSlice, ok := rest.([]interface{}); ok {
		for _, v := range restSlice {
			if arr, ok := v.([]interface{}); ok && len(arr) == 4 {
				if pat, ok := arr[3].(core.Pattern); ok {
					pats = append(pats, pat)
				}
			}
		}
	}
	return pats, nil
}

func (p *parser) callonPolymeterInner1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPolymeterInner1(stack["first"], stack["rest"])
}

func (c *current) onPolymeterSuffix2(n any) (any, error) {
	return "%" + n.(string), nil
}

func (p *parser) callonPolymeterSuffix2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPolymeterSuffix2(stack["n"])
}

func (c *current) onPolymeterSuffix8(n any) (any, error) {
	return "*" + n.(string), nil
}

func (p *parser) callonPolymeterSuffix8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPolymeterSuffix8(stack["n"])
}

func (c *current) onPolymeterSuffix14(n any) (any, error) {
	return "/" + n.(string), nil
}

func (p *parser) callonPolymeterSuffix14() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPolymeterSuffix14(stack["n"])
}

func (c *current) onWord1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonWord1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWord1()
}

func (c *current) onNumber1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonNumber1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onRest4() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonRest4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRest4()
}

func (c *current) onFastOp1(n any) (any, error) {
	return "*" + n.(string), nil
}

func (p *parser) callonFastOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFastOp1(stack["n"])
}

func (c *current) onSlowOp1(n any) (any, error) {
	return "/" + n.(string), nil
}

func (p *parser) callonSlowOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSlowOp1(stack["n"])
}

func (c *current) onEuclidOp1(pulses, steps any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonEuclidOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEuclidOp1(stack["pulses"], stack["steps"])
}

func (c *current) onWeightOp1(n any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonWeightOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWeightOp1(stack["n"])
}

func (c *current) onDegradeOp1(n any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonDegradeOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDegradeOp1(stack["n"])
}

func (c *current) onReplicateOp2(n any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonReplicateOp2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReplicateOp2(stack["n"])
}

func (c *current) onReplicateOp9() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonReplicateOp9() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReplicateOp9()
}

func (c *current) on_1() (any, error) {
	return "", nil
}

func (p *parser) callon_1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.on_1()
}

func (c *current) onEOF1() (any, error) {
	return "", nil
}

func (p *parser) callonEOF1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEOF1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
